<?php

namespace app\components;

use app\models\Log;
use app\models\Menu;
use devgroup\dropzone\DropZone;
use dosamigos\tinymce\TinyMce;
use Yii;
use yii\db\ActiveRecord;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\widgets\ActiveForm;

abstract class CustomActiveRecord extends ActiveRecord
{
    /* This fields for save system logs */
    protected $logging = true;
    protected $logModelID;
    protected $insertLogCode;
    protected $updateLogCode;
    protected $deleteLogCode;
    protected $searchLogCode;
    private $_old;

    /* end log */

    public function beforeSave($insert)
    {
        /* for log */
        $this->_old = $this->oldAttributes;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        /* save log process */
        if ($this->logging) {
            if ($insert && $this->insertLogCode) {
                $attributes = $this->attributes;
                if (isset($attributes['dyna']))
                    $attributes['dyna'] = $this->getDynamicAttributes();
                Log::create(Log::ACTION_INSERT,
                    $this->insertLogCode,
                    $this->tableName(),
                    $this->logModelID ? $this->{$this->logModelID} : $this->primaryKey,
                    Json::encode(['new' => $attributes])
                );
            } else if (!$insert && $this->updateLogCode)
                Log::create(Log::ACTION_UPDATE,
                    $this->updateLogCode,
                    $this->tableName(),
                    $this->logModelID ? $this->{$this->logModelID} : $this->primaryKey,
                    Json::encode(['old' => $changedAttributes, 'new' => $this->getNewValues($changedAttributes, $this->attributes)])
                );
        }
        /* end save log process */

        parent::afterSave($insert, $changedAttributes);
    }

    public function beforeDelete()
    {
        /* for log */
        $this->_old = $this->oldAttributes;
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        /* save log process */
        if ($this->logging && $this->deleteLogCode)
            @Log::create(Log::ACTION_DELETE,
                $this->deleteLogCode,
                $this->tableName(),
                $this->logModelID ? $this->{$this->logModelID} : $this->primaryKey,
                Json::encode(['old' => $this->_old])
            );
        /* save log process */

        parent::afterDelete();
    }

    public function afterFind()
    {
        /* save log process */
        if ($this->logging && $this->searchLogCode)
            @Log::create(Log::ACTION_SEARCH,
                $this->searchLogCode,
                $this->tableName(),
                $this->logModelID ? $this->{$this->logModelID} : $this->primaryKey
            );
        /* save log process */

        parent::afterFind();
    }

    public function getOld($changedAttributes)
    {
        $keys = array_keys($changedAttributes);
        return array_filter($this->_old, function ($key) use ($keys) {
            return in_array($key, $keys);
        }, ARRAY_FILTER_USE_KEY);
    }

    public function getNewValues($changedAttributes, $attributes)
    {
        $result = [];
        foreach (array_keys($changedAttributes) as $attributeName)
            $result[$attributeName] = $attributes[$attributeName];
        return $result;
    }


    /**************************************    Form Renderer    **************************************/
    const FORM_FIELD_TYPE_TEXT = 1;
    const FORM_FIELD_TYPE_TEXT_AREA = 2;
    const FORM_FIELD_TYPE_SWITCH = 3;
    const FORM_FIELD_TYPE_SELECT = 4;
    const FORM_FIELD_TYPE_CHECKBOX_LIST = 5;
    const FORM_FIELD_TYPE_RADIO_LIST = 6;
    const FORM_FIELD_TYPE_CHECKBOX = 7;
    const FORM_FIELD_TYPE_RADIO = 8;
    const FORM_FIELD_TYPE_TEXT_EDITOR = 9;
    const FORM_FIELD_TYPE_DROP_ZONE = 10;
    const FORM_FIELD_TYPE_DATETIME = 11;
    const FORM_FIELD_TYPE_DATE = 12;
    const FORM_FIELD_TYPE_TIME = 13;
    const FORM_FIELD_TYPE_TAG = 14;
    const FORM_FIELD_TYPE_PASSWORD = 15;

    /**
     * @return array
     */
    public function formAttributes()
    {
        return [];
    }

    /**
     * @param $form ActiveForm
     * @param string $template
     * @param string $allContainerCssClass
     * @return string
     */
    public function formRenderer($form, $template = '{field}', $allContainerCssClass = '')
    {
        $output = '';

        $fields = $this->formAttributes();
        foreach ($fields as $name => $field) {
            $labelEx = true;
            $label = '';
            if (isset($field['label'])) {
                $labelEx = false;
                $label = $field['label'];
                unset($field['label']);
            }

            $containerOptions = isset($field['containerOptions']) ? $field['containerOptions'] : [];
            unset($field['containerOptions']);
            $containerCssClass = isset($field['containerCssClass']) ? $field['containerCssClass'] : '';
            unset($field['containerCssClass']);

            $field['attribute'] = $name;
            $obj = $this->fieldRenderer($form, $field);
            if (!$labelEx) {
                $output .= strtr($template, ['{label}' => $label]);
                $obj->label(false);
            }

            Html::addCssClass($containerOptions, empty($containerCssClass)?$allContainerCssClass:$containerCssClass);
            $fieldHtml = Html::tag('div', $obj, $containerOptions);
            $output .= strtr($template, ['{field}' => $fieldHtml]);
        }

        return $output;
    }

    /**
     * @param $form ActiveForm
     * @param $field array
     * sample: [
     *      'model' => $model, // optional, if not set be $this
     *      'attribute' => ...,
     *      'type' => self::FORM_FIELD_TYPE_...,
     *      'options' => [...], // field htmlOptions
     * ]
     * @return \yii\widgets\ActiveField
     */
    public function fieldRenderer($form, $field)
    {
        $model = isset($field['model']) ? $field['model'] : $this;
        $options = isset($field['options']) ? $field['options'] : [];
        $fieldOptions = isset($field['fieldOptions']) ? $field['fieldOptions'] : [];
        $items = isset($field['items']) ? $field['items'] : [];
        $attribute = $field['attribute'];
        $type = isset($field['type']) ? $field['type'] : false;
        switch ($type) {
            case self::FORM_FIELD_TYPE_DROP_ZONE:
                return $form->field($model, $attribute)->widget(DropZone::className(), $options);
                break;
            case self::FORM_FIELD_TYPE_CHECKBOX:
                return $form->field($model, $attribute)->checkbox($options);
                break;
            case self::FORM_FIELD_TYPE_RADIO:
                return $form->field($model, $attribute)->radio($options);
                break;
            case self::FORM_FIELD_TYPE_CHECKBOX_LIST:
                return $form->field($model, $attribute)->checkboxList($items, $options);
                break;
            case self::FORM_FIELD_TYPE_RADIO_LIST:
                return $form->field($model, $attribute)->radioList($items, $options);
                break;
            case self::FORM_FIELD_TYPE_SELECT:
                return $form->field($model, $attribute)->dropDownList($items, $options);
                break;
            case self::FORM_FIELD_TYPE_SWITCH:
                if (!isset($fieldOptions['template']))
                    $fieldOptions['template'] = '{label}<label class="switch">{input}<span class="slider round"></span></label>{error}';
                return $form->field($model, $attribute, $fieldOptions)->checkbox([], false);
                break;
            case self::FORM_FIELD_TYPE_TEXT_EDITOR:
                return $form->field($model, $attribute, $fieldOptions)->widget(TinyMce::className(), $options);
                break;
            case self::FORM_FIELD_TYPE_TEXT_AREA:
                return $form->field($model, $attribute, $fieldOptions)->textarea($options);
                break;
            case self::FORM_FIELD_TYPE_PASSWORD:
                return $form->field($model, $attribute, $fieldOptions)->passwordInput($options);
                break;
            case self::FORM_FIELD_TYPE_TAG:
            case self::FORM_FIELD_TYPE_TIME:
            case self::FORM_FIELD_TYPE_DATE:
            case self::FORM_FIELD_TYPE_DATETIME:
            case self::FORM_FIELD_TYPE_TEXT:
            default:
                return $form->field($model, $attribute, $fieldOptions)->textInput($options);
                break;
        }
    }
}