<?php

namespace app\components\customWidgets;

use yii\captcha\CaptchaAction;

class CustomCaptchaAction extends CaptchaAction
{
    public $setTheme = false;
    public $onlyNumber = false;

    public function init()
    {
        if($this->setTheme)
            \Yii::$app->controller->setTheme('frontend', ['bodyClass' => 'innerPages']);
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function generateVerifyCode()
    {
        if(!$this->onlyNumber)
            return parent::generateVerifyCode();

        if ($this->minLength > $this->maxLength) {
            $this->maxLength = $this->minLength;
        }
        if ($this->minLength < 3) {
            $this->minLength = 3;
        }
        if ($this->maxLength > 8) {
            $this->maxLength = 8;
        }
        $length = mt_rand($this->minLength, $this->maxLength);
        $digits = '0123456789';
        $code = '';
        for ($i = 0; $i < $length; ++$i) {
            $code .= $digits[mt_rand(0, 9)];
        }
        return $code;
    }

    public function validate($input, $caseSensitive)
    {
        // Skip validation on AJAX requests, as it expires the captcha.
        if (\Yii::$app->request->isAjax) {
            return true;
        }
        return parent::validate($input, $caseSensitive);
    }
}