<?php

namespace app\components\customWidgets;

use yii\captcha\CaptchaAction;

class CustomCaptchaAction extends CaptchaAction
{
    public $setTheme = false;
    public function init()
    {
        if($this->setTheme)
            \Yii::$app->controller->setTheme('frontend', ['bodyClass' => 'innerPages']);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function validate($input, $caseSensitive)
    {
        // Skip validation on AJAX requests, as it expires the captcha.
        if (\Yii::$app->request->isAjax) {
            return true;
        }
        return parent::validate($input, $caseSensitive);
    }
}