<?php

namespace app\models;

use app\components\MultiLangActiveQuery;

/**
 * This is the ActiveQuery class for [[Item]].
 *
 * @see Item
 */
class ItemQuery extends MultiLangActiveQuery
{
    protected $_modelName = null;
    protected $_typeName = null;

    public function __construct($modelClass, array $config = [])
    {
        $this->_modelName = $modelClass::$modelName;
        $this->_typeName = $modelClass::$typeName;
        parent::__construct($modelClass, $config);
    }

    /**
     * {@inheritdoc}
     * @return Item[]|array
     */
    public function all($db = null)
    {
        $this->andWhere([
            'modelID' => Model::findOne(['name' => $this->_modelName])->id
        ]);

        if ($this->_typeName) {
            $this->andWhere([
                'type' => $this->_typeName
            ]);
        }

        return parent::all($db);
    }

    public function count($q = '*', $db = null)
    {
        $this->andWhere([
            'modelID' => Model::findOne(['name' => $this->_modelName])->id
        ]);

        if ($this->_typeName) {
            $this->andWhere([
                'type' => $this->_typeName
            ]);
        }

        return parent::count($q, $db); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return Item|array|null
     */
    public function one($db = null)
    {
        $this->andWhere([
            'modelID' => Model::findOne(['name' => $this->_modelName])->id
        ]);

        if ($this->_typeName) {
            $this->andWhere([
                'type' => $this->_typeName
            ]);
        }

        return parent::one($db);
    }

    public function valid()
    {
        $this->andWhere(['status' => Item::STATUS_PUBLISHED]);
        return $this;
    }
}